version: '3.8'
services:
  nginx:
    build:
      context: ./docker/development/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker/development/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/app
  php-cli:
    build:
      context: ./docker/development/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - manager-composer:/root/.composer/cache
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - manager-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
  mailer:
    image: mailhog/mailhog
    ports:
      - '8081:8025'
  node:
    image: node:16.14-alpine
    volumes:
      - ./:/app
    working_dir: /app
  node-watch:
    image: node:16.14-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"

volumes:
  manager-postgres:
  manager-composer: