version: '3.8'
services:
  nginx:
    build:
      context: ./docker/development/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker/development/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/app
  php-cli:
    build:
      context: ./docker/development/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - composer:/root/.composer/cache

volumes:
  postgres:
  redis:
  queue-redis:
  composer: